# different stages for the CICD pipeline
stages:
  # 1st stage
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/insurance.csv
    outs:
    - data/raw/insurance.csv
  # 2nd stage
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/insurance.csv
    outs:
      - data/processed/train_insurance.csv
      - data/processed/test_insurance.csv
  
  # stage 3
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_insurance.csv
    - data/processed/test_insurance.csv
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false
    outs:
    - saved_models/model.joblib

  
  